// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFQlaPCWlOuPh7R0Sml2HLyLG3WhqQ6zk',
    appId: '1:3434521697:web:b5f9c74fbf80ee447df620',
    messagingSenderId: '3434521697',
    projectId: 'lucky-bag-community',
    authDomain: 'lucky-bag-community.firebaseapp.com',
    storageBucket: 'lucky-bag-community.appspot.com',
    measurementId: 'G-KL2CFCCSM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPUm9DjOTRPh90bQ6jIEJu-0nU21-LC0Y',
    appId: '1:3434521697:android:51a0cfed88ecfe8e7df620',
    messagingSenderId: '3434521697',
    projectId: 'lucky-bag-community',
    storageBucket: 'lucky-bag-community.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB83GQ_CYeTWFMX9TVT-NkCMyWTwXX_VXs',
    appId: '1:3434521697:ios:38b1ed1a95ba3d877df620',
    messagingSenderId: '3434521697',
    projectId: 'lucky-bag-community',
    storageBucket: 'lucky-bag-community.appspot.com',
    iosClientId: '3434521697-1ohmlplgvis61mk2rq9d5iodsv2615f1.apps.googleusercontent.com',
    iosBundleId: 'com.example.rehearsalPay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB83GQ_CYeTWFMX9TVT-NkCMyWTwXX_VXs',
    appId: '1:3434521697:ios:38b1ed1a95ba3d877df620',
    messagingSenderId: '3434521697',
    projectId: 'lucky-bag-community',
    storageBucket: 'lucky-bag-community.appspot.com',
    iosClientId: '3434521697-1ohmlplgvis61mk2rq9d5iodsv2615f1.apps.googleusercontent.com',
    iosBundleId: 'com.example.rehearsalPay',
  );
}
